### ISSUE TITLE
TODO:  Get all reviews of product

### ISSUE THREAD

**Issue by ShukuraliProgrammer** [ShukuraliProgrammer/e-commerce#12]

**Comment by DevSleek** [comment]
Assalomu aleykum men qilib beraman qo'shib quyaolasizmi

**Comment by ShukuraliProgrammer** [comment]
@DevSleek sizga task biriktirildi, endi yangi branch ochib ushanga push qilasiz. Branch nomini task ga moslab quying misol uchun product_review

**Comment by DevSleek** [comment]
Aha ho'p

**Comment by DevSleek** [comment]
githubga push qilishda username i password surayabdi

**Comment by ShukuraliProgrammer** [comment]
> githubga push qilishda username i password surayabdi

uziznikini kiritib push qilasizda

**Comment by DevSleek** [comment]
bo'lmadi

**Comment by DevSleek** [comment]
contributorlarga qo'shing

**Comment by ShukuraliProgrammer** [comment]
> bo'lmadi

nima dedi ?

**Comment by DevSleek** [comment]
![Screenshot from 2024-05-17 19-13-12](https://github.com/ShukuraliProgrammer/e-commerce/assets/104163417/41a1277d-6f5c-4392-8fbf-e6d8b4c4a3cb)

**Comment by DevSleek** [comment]
siz contributorlarga qo'shsiz qilaolaman o'zimini usernam i passwordim orqali

**Comment by DevSleek** [comment]
yangi branch yaratib push qildim ko'rasizmi

**Comment by ShukuraliProgrammer** [comment]
pull request ham yarating from your_new_branch to main

**Comment by DevSleek** [comment]
kodim to'g'rimi qilaveraymi

**Comment by DevSleek** [comment]
![Screenshot from 2024-05-20 06-41-10](https://github.com/ShukuraliProgrammer/e-commerce/assets/104163417/46ba6379-5c9d-40e9-b9e5-1453b586bbc1)
merge qilolmadim faqat pull bo'ldi

**Comment by ShukuraliProgrammer** [comment]
> ![Screenshot from 2024-05-20 06-41-10](https://private-user-images.githubusercontent.com/104163417/331918797-46ba6379-5c9d-40e9-b9e5-1453b586bbc1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYzOTU2MjgsIm5iZiI6MTcxNjM5NTMyOCwicGF0aCI6Ii8xMDQxNjM0MTcvMzMxOTE4Nzk3LTQ2YmE2Mzc5LTVjOWQtNDBlOS1iOWU1LTE0NTNiNTg2YmJjMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyMlQxNjI4NDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wZGE1YTM2NDk4MmE5NzlkNjJkMTc2YmYwNzMzMzJmNDBjYWI1YTgyNzQ4MjJjZDMxMjA3MjljNzcxODUxNTY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.DE7oGQd6T3E7hM7Vdruu4TY7aiXuYoj4JVfYncXKjV8) merge qilolmadim faqat pull bo'ldi

qilishga urinmang, men uzim qilaman

**Comment by ShukuraliProgrammer** [comment]
Bu issue yopildi

**Comment by DevSleek** [comment]
man o'zim qilgandim shakelli
