### ISSUE TITLE
TODO: Related products to one product

### ISSUE THREAD

**Issue by ShukuraliProgrammer** [ShukuraliProgrammer/e-commerce#13]
Bu bir productga aloqador, o'xshash productlar hisoblanadi va bular product detail api da chiqishi kerak yoki alohida.

**Comment by abduqodir5555** [comment]
Assalom alaykum men bu taskni qilmoqchi edim

**Comment by ShukuraliProgrammer** [comment]
> Assalom alaykum men bu taskni qilmoqchi edim

sizga biriktirib quydim boshlasangiz bo'ladi

**Comment by ShukuraliProgrammer** [comment]
task yopildi
